SELECT 
  PRINCIPAL.WORk_ZONE, PRINCIPAL.LOCATION, PRINCIPAL.ITEM, PRINCIPAL.ITEM_DESC, PRINCIPAL.COMPANY,
  CAST(SUM(AV) AS INT) AS AV,
  CAST(SUM(OH) AS INT) AS OH,
  CAST(SUM(AL) AS INT) AS AL,
  CAST(SUM(IT) AS INT) AS IT,
  CAST(SUM(SU) AS INT) AS SU,
  CAST((SUM(OH) / UOM.conversion_qty) AS DECIMAL(5, 2)) AS CAJAS,
  CASE
        WHEN COUNT(LICENSE_PLATE) = 0 THEN ''
        WHEN COUNT(LICENSE_PLATE) > 1 THEN 'Multiple'
        ELSE MAX(LICENSE_PLATE)
    END AS LICENSE_PLATE

FROM (
 SELECT
    L.WORk_ZONE,
    LI.LOCATION,
    LI.ITEM,
    REPLACE(LI.ITEM_DESC, ',', '.') AS ITEM_DESC,
    LI.COMPANY,
    ((LI.ON_HAND_QTY + LI.IN_TRANSIT_QTY) -  (LI.ALLOCATED_QTY + LI.SUSPENSE_QTY)) AS AV,
    LI.ON_HAND_QTY AS OH,
    LI.ALLOCATED_QTY AS AL,
    LI.IN_TRANSIT_QTY AS IT,
    LI.SUSPENSE_QTY AS SU,
    LI.logistics_Unit AS LICENSE_PLATE,
    LI.internal_location_inv
 

  FROM location_inventory LI
  INNER JOIN location L
  ON L.location = LI.location

  WHERE L.location_type LIKE 'Gene%'
  AND L.warehouse='Mariano'
  AND LI.warehouse='Mariano'
  AND LI.company <> 'AMD'
  AND L.work_zone = 'W-Mar Bodega 2' 
  -- AND L.location LIKE '1%'
  -- AND LI.item IN ( )

  GROUP BY LI.LOCATION, LI.ITEM, LI.ITEM_DESC, LI.COMPANY, LI.ON_HAND_QTY, LI.ALLOCATED_QTY, LI.IN_TRANSIT_QTY, LI.SUSPENSE_QTY, LI.internal_location_inv, L.work_zone, L.warehouse, L.location_type, LI.logistics_Unit
) AS PRINCIPAL

LEFT OUTER JOIN item_unit_of_measure UOM ON PRINCIPAL.ITEM=UOM.item AND UOM.sequence='2' AND UOM.company='FM'

GROUP BY PRINCIPAL.WORk_ZONE, PRINCIPAL.LOCATION, PRINCIPAL.ITEM, PRINCIPAL.ITEM_DESC, PRINCIPAL.COMPANY, UOM.conversion_qty

ORDER BY PRINCIPAL.WORk_ZONE, PRINCIPAL.LOCATION, PRINCIPAL.ITEM

-- WORK_ZONE,LOCATION,ITEM,ITEM_COLOR,COMPANY,AV,OH,AL,IT,SU,LICENSE_PLATE,


