SELECT
  L.WORK_ZONE,
  LI.LOCATION,
  LI.ITEM,
  REPLACE(LI.ITEM_DESC, ',', '.') AS DESCRIPTION,
  LI.COMPANY,
  CAST(((LI.ON_HAND_QTY + LI.IN_TRANSIT_QTY) - (LI.ALLOCATED_QTY + LI.SUSPENSE_QTY)) AS INT) AS AV,
  CAST(LI.ON_HAND_QTY AS INT) AS OH,
  CAST(LI.ALLOCATED_QTY AS INT) AS AL,
  CAST(LI.IN_TRANSIT_QTY AS INT) AS IT,
  CAST(LI.SUSPENSE_QTY AS INT) AS SU,
  LI.logistics_Unit AS LICENCE_PLATE,

FROM location_inventory LI
INNER JOIN location L
 ON L.location = LI.location

WHERE L.location_type LIKE 'Gene%'
AND L.warehouse='Mariano'
AND L.work_zone = 'W-Mar Bodega 2' 
-- AND L.location LIKE '1%'
AND item IN ( )

ORDER BY L.WORK_ZONE, LI.LOCATION, LI.ITEM

-- WORK_ZONE,LOCATION,ITEM,DESCRIPTION,COMPANY,AV,OH, AL, IT, SU, LICENCE_PLATE,