SELECT 
  ITEM,
  DESCRIPTION,
  SUM(CANTIDAD) AS PIEZAS,
  (SUM(CANTIDAD) / HUELLA) AS CAJAS,
  COMPANY,
  TIPO_DE_RECIBO,
  CONVERT(varchar, DATEADD(hour, -6, DATE_RECEIPT), 6) AS FECHA,
  ZONA
  
FROM (
  SELECT
  WI.REFERENCE_ID AS ID_RECIBO,
  WI.ITEM AS ITEM,
  REPLACE(WI.ITEM_DESC, ',', '.') AS DESCRIPTION,
  (CAST(WI.FROM_QTY AS INT) + CAST(WI.TO_QTY AS INT)) AS CANTIDAD,
  CAST(UOM.conversion_qty AS INT) AS HUELLA,
  RH.receipt_date AS DATE_RECEIPT,
  WI.work_unit AS UNIDAD_DE_TRABAJO,
  WI.COMPANY AS COMPANY,
  CASE 
    WHEN WI.TO_WORK_ZONE LIKE '%Primer%' OR  WI.LOCATING_ZONE LIKE '%Primer%' THEN '1'
    WHEN WI.TO_WORK_ZONE LIKE '%Segundo%' OR  WI.LOCATING_ZONE LIKE '%Segundo%' THEN '2'
    ELSE  '-' END AS ZONA,
  CASE 
   WHEN RH.RECEIPT_ID_TYPE  = 'Importacion' THEN  RH.RECEIPT_ID_TYPE
   WHEN RH.RECEIPT_ID_TYPE = 'Nacional' AND RH.RECEIPT_ID LIKE '%PICOS%' THEN 'Picos'
   WHEN RH.RECEIPT_ID_TYPE = 'Nacional' AND RH.INTERFACE_RECORD_ID IS NOT NULL THEN 'Tulti'
   WHEN RH.RECEIPT_ID_TYPE = 'Nacional' THEN  RH.RECEIPT_ID_TYPE
   WHEN RH.RECEIPT_ID_TYPE = 'DEV-TDA-ME' THEN  'Devolucion'
   ELSE RH.RECEIPT_ID_TYPE END AS TIPO_DE_RECIBO


  FROM Work_instruction WI
  INNER JOIN receipt_header RH ON RH.RECEIPT_ID = WI.REFERENCE_ID
  INNER JOIN Item_unit_of_measure UOM ON WI.ITEM = UOM.item AND UOM.sequence='2'

  WHERE WI.WORK_TYPE LIKE 'Almacenaje%'
  AND WI.INSTRUCTION_TYPE = 'Detail'
  AND WI.FROM_WHS = 'Mariano'
  AND WI.CONDITION <> 'Closed'
  AND RH.WAREHOUSE = 'Mariano'

  GROUP BY 
  WI.REFERENCE_ID, WI.ITEM, WI.ITEM_DESC, WI.FROM_QTY, WI.TO_QTY, WI.INSTRUCTION_TYPE, 
  WI.TO_WORK_ZONE, WI.WORK_TYPE, WI.FROM_WHS, WI.internal_instruction_num, WI.LOCATING_ZONE,
  WI.work_unit, WI.COMPANY,
  RH.RECEIPT_ID, RH.WAREHOUSE, RH.receipt_date, RH.RECEIPT_ID_TYPE, RH.INTERFACE_RECORD_ID,
  UOM.conversion_qty
) AS PRINCIPAL

GROUP BY
ITEM,
DESCRIPTION,
DATE_RECEIPT,
TIPO_DE_RECIBO,
COMPANY,
ZONA,
HUELLA

-- ITEM,DESCRIPTION,PIEZAS,CAJAS,COMPANY,TIPO_DE_RECIBO,FECHA_DE_RECIBO,ZONA,

ORDER BY ZONA ASC, DATE_RECEIPT ASC
