SELECT 
    WORK_UNIT, PEDIDO
FROM 
(
    SELECT 
        WORK_UNIT, PEDIDO = REFERENCE_ID, LAUNCH_NUM

    FROM work_instruction
    WHERE LAUNCH_NUM = '1228415'
        AND INSTRUCTION_TYPE = 'Header'

    UNION ALL

    SELECT DISTINCT
        WORK_UNIT = 'CORTO', PEDIDO = SHIPMENT_ID, PREVIOUS_WAVE_NUM
    FROM shipment_detail

    WHERE PREVIOUS_WAVE_NUM = '1228415'
        AND STATUS1 = 100
        AND ALLOCATION_REJECTED_QTY > 0
) AS CombinedResult;