INSERT INTO ITEM_LOCATION_ASSIGNMENT (warehouse, ITEM, COMPANY, QUANTITY_UM, ALLOCATION_LOC, USER_STAMP, DATE_TIME_STAMP)
VALUES 
-- ('Mariano', 'ITEM', 'FM', 'PZ', 'LOCATION', 'JoseCarlos', DATEADD(HOUR, 6, GETDATE())),

