INSERT INTO item_cross_reference (ITEM, X_REF_ITEM, COMPANY, USER_STAMP, DATE_TIME_STAMP, QUANTITY_UM, GTIN_ENABLED)
VALUES 
-- ('ITEM', 'CODIGO_DE_BARRAS', 'FM', 'JoseCarlos', DATEADD(HOUR, 6, GETDATE()), 'PZ', 'N'),

