SELECT 
  ITEM,
  DESCRIPTION,
  UOM_PZ,
  LARGO_PZ,
  ANCHO_PZ,
  ALTURA_PZ,
  DIMS_OK_PARA_BANDA_PZ,
  LARGO_PZ_OK,
  ANCHO_PZ_OK,
  ALTURA_PZ_OK,
  UOM_CJ,
  LARGO_CJ,
  ANCHO_CJ,
  ALTURA_CJ,
  DIMS_OK_PARA_BANDA_CJ,
  LARGO_CJ_OK,
  ANCHO_CJ_OK,
  ALTURA_CJ_OK,
  CASE 
    WHEN DIMS_OK_PARA_BANDA_PZ <> 'OK' AND  DIMS_OK_PARA_BANDA_CJ <> 'OK' THEN 'AMBOS'
    WHEN DIMS_OK_PARA_BANDA_PZ = 'OK' AND  DIMS_OK_PARA_BANDA_CJ <> 'OK' THEN 'PZ_OK'
    WHEN DIMS_OK_PARA_BANDA_PZ <> 'OK' AND  DIMS_OK_PARA_BANDA_CJ = 'OK' THEN 'CJ_OK'
    ELSE '' END OK

FROM (
  SELECT  
  I.ITEM,
 REPLACE( I.DESCRIPTION, ',', '')  AS DESCRIPTION,
  MAX(CASE WHEN UOM.QUANTITY_UM = 'PZ' THEN 'PZ' END) AS UOM_PZ,
  MAX(CASE WHEN UOM.QUANTITY_UM = 'PZ' THEN CAST(UOM.LENGTH AS DECIMAL(10, 2)) END) AS LARGO_PZ,

  MAX(CASE WHEN UOM.QUANTITY_UM = 'PZ' THEN CAST(UOM.WIDTH AS DECIMAL(10, 2)) END) AS ANCHO_PZ,
  MAX(CASE WHEN UOM.QUANTITY_UM = 'PZ' THEN CAST(UOM.HEIGHT AS DECIMAL(10, 2)) END) AS ALTURA_PZ,
  MAX(CASE WHEN UOM.QUANTITY_UM = 'PZ' 
           AND UOM.LENGTH <= 70 AND UOM.WIDTH <= 58 AND UOM.HEIGHT <= 69 THEN 'OK' 
           WHEN UOM.QUANTITY_UM = 'PZ' THEN 'AFUERA DE LIMITES' 
           ELSE '' END) AS DIMS_OK_PARA_BANDA_PZ,

  MAX(CASE WHEN  UOM.QUANTITY_UM = 'PZ' AND UOM.LENGTH <= 70  THEN 'OK' ELSE 'LIMITE' END) AS  LARGO_PZ_OK,
  MAX(CASE WHEN  UOM.QUANTITY_UM = 'PZ' AND UOM.WIDTH <= 58 THEN 'OK' ELSE 'LIMITE' END)  AS ANCHO_PZ_OK,
  MAX(CASE WHEN  UOM.QUANTITY_UM = 'PZ' AND UOM.HEIGHT <= 69 THEN 'OK' ELSE 'LIMITE' END)  AS ALTURA_PZ_OK,
  
  MAX(CASE WHEN UOM.QUANTITY_UM = 'CJ' THEN 'CJ' END) AS UOM_CJ,
  MAX(CASE WHEN UOM.QUANTITY_UM = 'CJ' THEN CAST(UOM.LENGTH AS DECIMAL(10, 2)) END) AS LARGO_CJ,
  MAX(CASE WHEN UOM.QUANTITY_UM = 'CJ' THEN CAST(UOM.WIDTH AS DECIMAL(10, 2)) END) AS ANCHO_CJ,
  MAX(CASE WHEN UOM.QUANTITY_UM = 'CJ' THEN CAST(UOM.HEIGHT AS DECIMAL(10, 2)) END) AS ALTURA_CJ,
  MAX(CASE WHEN UOM.QUANTITY_UM = 'CJ' 
           AND UOM.LENGTH <= 70 AND UOM.WIDTH <= 58 AND UOM.HEIGHT <= 69 THEN 'OK' 
           WHEN UOM.QUANTITY_UM = 'CJ' THEN 'AFUERA DE LIMITES' 
           ELSE '' END) AS DIMS_OK_PARA_BANDA_CJ,

    MAX(CASE WHEN  UOM.QUANTITY_UM = 'CJ' AND UOM.LENGTH <= 70  THEN 'OK' ELSE 'LIMITE' END) AS  LARGO_CJ_OK,
  MAX(CASE WHEN  UOM.QUANTITY_UM = 'CJ' AND UOM.WIDTH <= 58 THEN 'OK' ELSE 'LIMITE' END)  AS ANCHO_CJ_OK,
  MAX(CASE WHEN  UOM.QUANTITY_UM = 'CJ' AND UOM.HEIGHT <= 69 THEN 'OK' ELSE 'LIMITE' END)  AS ALTURA_CJ_OK

  FROM 
    ITEM I
    LEFT JOIN Item_unit_of_measure UOM ON I.ITEM = UOM.ITEM
  WHERE 
    I.COMPANY = 'FM' 
    AND (I.ITEM_CATEGORY1 <> 'Bulk' OR I.ITEM_CATEGORY1 IS NULL)
    AND I.ITEM_CATEGORY3 = 'BANDA'
    AND UOM.COMPANY = 'FM'
    AND UOM.sequence <> '3'
    AND NOT (I.DESCRIPTION LIKE '/Mty%' OR  I.DESCRIPTION LIKE '/Mtc%'  OR I.DESCRIPTION LIKE '/Gdl%'  OR I.DESCRIPTION LIKE '/Tij%')

  GROUP BY 
    I.ITEM, 
    I.DESCRIPTION
) AS CP

WHERE NOT (DIMS_OK_PARA_BANDA_PZ = 'OK' AND  DIMS_OK_PARA_BANDA_CJ ='OK')
AND NOT (DIMS_OK_PARA_BANDA_PZ = 'OK' AND  DIMS_OK_PARA_BANDA_CJ ='')
AND NOT (DIMS_OK_PARA_BANDA_PZ = '' AND  DIMS_OK_PARA_BANDA_CJ ='OK');

--  ITEM,DESCRIPTION,UOM_PZ,LARGO_PZ,ANCHO_PZ,ALTURA_PZ,DIMS_OK_PARA_BANDA_PZ,LARGO_PZ_OK,ANCHO_PZ_OK,ALTURA_PZ_OK,UOM_CJ,LARGO_CJ,ANCHO_CJ,ALTURA_CJ,DIMS_OK_PARA_BANDA_CJ,LARGO_CJ_OK,ANCHO_CJ_OK,ALTURA_CJ_OK,OK,

UPDATE Item_unit_of_measure
SET LENGTH = 70
-- SET WIDTH = 58
-- SET HEIGHT = 69


WHERE COMPANY = 'FM'
-- AND sequence <> '3'
AND sequence = '2'
AND ITEM IN (
  
);
