SELECT 
  ID_RECIBO,
  ITEM,
  SUM(CANTIDAD) AS TOTAL,
  FECHA_DE_RECIBO,
  PISO
  
FROM (
  SELECT
  WI.REFERENCE_ID AS ID_RECIBO,
  WI.ITEM AS ITEM,
  REPLACE(WI.ITEM_DESC, ',', '.') AS DESCRIPCION,
  (CAST(WI.FROM_QTY AS INT) + CAST(WI.TO_QTY AS INT)) AS CANTIDAD,
  CONVERT(varchar, RH.receipt_date,103) AS FECHA_DE_RECIBO,
  WI.work_unit AS UNIDAD_DE_TRABAJO,
  CASE 
    WHEN WI.TO_WORK_ZONE LIKE '%Primer%' OR  WI.LOCATING_ZONE LIKE '%Primer%' THEN '1'
    WHEN WI.TO_WORK_ZONE LIKE '%Segundo%' OR  WI.LOCATING_ZONE LIKE '%Segundo%' THEN '2'
    ELSE  '' END AS PISO


  FROM Work_instruction WI
  INNER JOIN receipt_header RH ON RH.RECEIPT_ID = WI.REFERENCE_ID


  WHERE WI.WORK_TYPE LIKE 'Almacenaje%'
  AND WI.INSTRUCTION_TYPE = 'Detail'
  AND WI.FROM_WHS = 'Mariano'
  AND RH.WAREHOUSE = 'Mariano'

  GROUP BY 
  WI.REFERENCE_ID, WI.ITEM, WI.ITEM_DESC, WI.FROM_QTY, WI.TO_QTY, WI.INSTRUCTION_TYPE, 
  WI.TO_WORK_ZONE, WI.WORK_TYPE, WI.FROM_WHS, WI.internal_instruction_num, WI.LOCATING_ZONE,
  WI.work_unit,
  RH.RECEIPT_ID, RH.WAREHOUSE, RH.receipt_date
) AS PRINCIPAL

GROUP BY
ID_RECIBO,
ITEM,
FECHA_DE_RECIBO,
PISO

-- ID_RECIBO, ITEM, TOTAL, FECHA_DE_RECIBO, PISO