SELECT 
  ITEM, COMPANY, SINCERO, CONCERO, COMP 
  
FROM (
SELECT 
  ITEM, 
  COMPANY, 
  MAX(SINCERO) AS SINCERO, 
  MAX(CONCERO) AS CONCERO,
  CASE WHEN CONCAT('0', MAX(SINCERO)) = MAX(CONCERO) THEN 'IGUAL' 
      WHEN (MAX(SINCERO) <> '' AND MAX(CONCERO) <> '') THEN 'AMBOS'
  ELSE '' END AS COMP 

FROM (
  SELECT 
    ICR.item AS ITEM,
    CASE WHEN ICR.X_REF_ITEM LIKE '7%' THEN ICR.X_REF_ITEM ELSE '' END AS SINCERO,
    CASE WHEN ICR.X_REF_ITEM LIKE '07%' THEN ICR.X_REF_ITEM ELSE '' END AS CONCERO,
    ICR.X_REF_ITEM AS CODIGO,
    ICR.company AS COMPANY,
    ICR.internal_item_cross_num
  FROM item_cross_reference ICR
  WHERE ICR.company <> 'AMD'
    AND ( ICR.X_REF_ITEM LIKE '7%' OR ICR.X_REF_ITEM LIKE '07%')
    
    -- AND (ICR.item LIKE '9507-%' OR ICR.item LIKE '9311-%')
) AS PRINCIPAL

GROUP BY ITEM, COMPANY
) AS SECONDARY

WHERE COMP = ''

GROUP BY ITEM, COMPANY, SINCERO, CONCERO, COMP
