SELECT
    ERP_ORDER,
    ARTICULO,
    DESCRIPCION,
    CAST(CORTO AS INT) AS CORTO,
    CAST(SUM(PENDIENTE_POR_SURTIR) AS INT) AS POR_SURTIR,
    CAST(SUM(SURTIENDOSE) AS INT) AS SURTIENDOSE,
    CAST(SUM(PENDIENTE_POR_CARGAR) AS INT) AS POR_CARGAR,
    CAST(SUM(PENDIENTE_POR_ENVIAR) AS INT) AS PENDIENTE_POR_ENVIAR,
    CAST(SUM(ENVIADO.TOTAL_QTY) AS INT) AS ENVIADO,
    CAST(MAX(TOTAL) AS INT) AS TOTAL,
    ORDER_DATE AS FECHA_ENVIO

-- Subconsulta Principal
FROM ( 
  SELECT 
    SD.ERP_ORDER AS ERP_ORDER,
    SD.ITEM AS ARTICULO, 
    SUBSTRING(SD.item_desc, 1, 15) AS DESCRIPCION, 
    MAX(SD.REQUESTED_QTY) AS TOTAL,
    CASE WHEN SD.status1 = 900 AND SD.ALLOCATION_REJECTED_QTY = 0 THEN SD.TOTAL_QTY ELSE 0 END AS ENVIADO,
    CASE WHEN SD.status1 <= 301 AND SD.ALLOCATION_REJECTED_QTY = 0 THEN SD.TOTAL_QTY ELSE 0 END AS PENDIENTE_POR_SURTIR,
    CASE WHEN SD.status1 > 301 AND SD.status1 < 650 AND SD.ALLOCATION_REJECTED_QTY = 0 THEN SD.TOTAL_QTY ELSE 0 END AS SURTIENDOSE,
    CASE WHEN SD.status1 = 650 AND SD.ALLOCATION_REJECTED_QTY = 0 THEN SD.TOTAL_QTY ELSE 0 END AS PENDIENTE_POR_CARGAR,
    CASE WHEN SD.status1 = 700 AND SD.ALLOCATION_REJECTED_QTY = 0 THEN SD.TOTAL_QTY ELSE 0 END AS PENDIENTE_POR_ENVIAR,
    CONVERT(varchar, SD.ORDER_DATE, 100) as ORDER_DATE,
    CONVERT(varchar, SD.PLANNED_SHIP_DATE, 100) as PLANNED_SHIP_DATE,
    SD.INTERNAL_SHIPMENT_LINE_NUM

  FROM  
    shipment_detail SD
  INNER JOIN 
    shipment_header SH ON SH.Shipment_id = SD.Shipment_id

  WHERE 
    SD.warehouse = 'Tultitlan'
    AND SH.order_type = 'TR-TUL-ME'
    AND SD.status1 <> 999
    AND SD.status1 <> 900
    AND SD.ERP_ORDER IN (SELECT DISTINCT SHIPMENT_ID
      FROM shipment_header
      WHERE order_type = 'TR-TUL-ME'
      AND Shipment_id NOT LIKE '%PICOS%')

  GROUP BY 
    SD.ERP_ORDER,
    SD.ITEM,
    SD.item_desc,
    SD.TOTAL_QTY,
    SD.QUANTITY_AT_STS2,
    SD.status1,
    SD.ORDER_DATE,
    SD.PLANNED_SHIP_DATE,
    SD.INTERNAL_SHIPMENT_LINE_NUM,
    SD.ALLOCATION_REJECTED_QTY
) AS CP

-- ENVIADO
LEFT OUTER JOIN (
  SELECT
    SD.ERP_ORDER AS ERP_ORDER_ENVIADO,
    SD.TOTAL_QTY AS TOTAL_QTY,
    SD.ITEM AS ITEM

    FROM  
    shipment_detail SD
  INNER JOIN 
    shipment_header SH ON SH.Shipment_id = SD.Shipment_id

  WHERE 
    SD.warehouse = 'Tultitlan'
    AND SH.order_type = 'TR-TUL-ME'
    AND SD.status1 = 900
    AND SD.ALLOCATION_REJECTED_QTY = 0
    AND SD.ERP_ORDER IN (SELECT DISTINCT SHIPMENT_ID
      FROM shipment_header
      WHERE order_type = 'TR-TUL-ME'
      AND Shipment_id NOT LIKE '%PICOS%')

  GROUP BY 
    SD.ERP_ORDER,
    SD.ITEM,
    SD.TOTAL_QTY,
    SD.status1,
    SD.ORDER_DATE,
    SD.INTERNAL_SHIPMENT_LINE_NUM,
    SD.ALLOCATION_REJECTED_QTY
) AS ENVIADO ON ENVIADO.ERP_ORDER_ENVIADO = CP.ERP_ORDER AND ENVIADO.ITEM = CP.ARTICULO

-- CORTOS
LEFT OUTER JOIN 
(
  SELECT 
  SD.item AS ITEM, 
  SD.status1 AS STATUS1,
  SD.TOTAL_QTY AS CORTO

  FROM  shipment_detail SD

  WHERE SD.status1=100 
  AND SD.ALLOCATION_REJECTED_QTY > 0
  AND SD.company='FM'
  AND SD.warehouse='Tultitlan'

  GROUP BY 
    SD.item,
    SD.status1,
    SD.ALLOCATION_REJECTED_QTY,
    SD.internal_shipment_line_num,
    SD.TOTAL_QTY 
  
) AS CORTOS
 ON CORTOS.ITEM=CP.ARTICULO

GROUP BY
    ERP_ORDER,
    ARTICULO,
    DESCRIPCION,
    ORDER_DATE,
    PLANNED_SHIP_DATE,
    CORTO

ORDER BY
  FECHA_ENVIO,
  ERP_ORDER,
  ARTICULO DESC

-- ERP_ORDER,ARTICULO,DESCRIPCION,CORTO,POR_SURTIR,SURTIENDOSE,POR_CARGAR,POR_ENVIAR,ENVIADO,TOTAL,FECHA_ENVIO,
