SELECT 
    ITEM,
    MAX(LOC_CJ) AS LOC_CJ,
    MAX(LOC_PZ) AS LOC_PZ

FROM (
    SELECT 
        item AS ITEM, 
        CASE WHEN QUANTITY_UM = 'CJ' THEN ALLOCATION_LOC ELSE NULL END AS LOC_CJ,
        CASE WHEN QUANTITY_UM = 'PZ' THEN ALLOCATION_LOC ELSE NULL END AS LOC_PZ
    FROM item_location_assignment   
    WHERE NOT (item LIKE '4110-%' OR item LIKE '1310-%' OR item LIKE '1346-%')
) AS PRINCIPAL

GROUP BY ITEM
HAVING 
      MAX(LOC_CJ) IS NOT NULL 
  AND MAX(LOC_PZ) IS NOT NULL 
  AND MAX(LOC_CJ) <> MAX(LOC_PZ);
