SELECT SD.PREVIOUS_WAVE_NUM AS OLA, WORK_ZONE AS BODEGA, SHIPMENT_ID AS PEDIDO,SD.ITEM AS ARTICULO, ALLOCATION_REJECTED_QTY AS RECHAZADA, 
    CASE WHEN LI.PERMANENT = 'N' THEN 'No tiene ubicación' ELSE MAX(LI.LOCATION) END AS UBICACION, 
	SUM(ON_HAND_QTY) AS OH, SUM(ALLOCATED_QTY) AS AL, SUM(IN_TRANSIT_QTY) AS IT, SUM(SUSPENSE_QTY) AS SU,
	CASE WHEN TOTAL_QTY_OK_MAR IS NULL THEN 0 ELSE TOTAL_QTY_OK_MAR END AS MAR,
	CASE WHEN TOTAL_QTY_OK_TUL IS NULL THEN 0 ELSE TOTAL_QTY_OK_TUL END AS TUL,
	CASE WHEN TOTAL_QTY_PRE01_MAR IS NULL THEN 0 ELSE TOTAL_QTY_PRE01_MAR END AS PRE, LS.LAUNCH_DATE_TIME_STARTED AS FECHA,
	CASE WHEN WI.WORK_TYPE = 'Reabasto Ola' THEN WI.WORK_UNIT ELSE 'Hacer transferencia' END AS UNIDAD_DE_TRABAJO

	FROM SHIPMENT_DETAIL SD

	LEFT JOIN LOCATION_INVENTORY LI ON LI.ITEM = SD.ITEM and LI.COMPANY = SD.COMPANY

	LEFT OUTER JOIN LOCATION L ON L.LOCATION = LI.LOCATION and L.warehouse =LI.warehouse 

	LEFT OUTER JOIN LAUNCH_STATISTICS LS ON LS.INTERNAL_LAUNCH_NUM = SD.PREVIOUS_WAVE_NUM



	LEFT OUTER JOIN ( select item,sum(on_hand_qty) AS TOTAL_QTY_OK_MAR
	 from LOCATION_INVENTORY LI
	 left outer join location L on L.location = LI.LOCATION
	 where LI.warehouse  = 'Mariano' AND L.location_CLASS = 'Inventory'	
	 group by LI.ITEM) OKMAR ON OKMAR.ITEM = SD.ITEM



	 LEFT OUTER JOIN ( select item,sum(on_hand_qty) AS TOTAL_QTY_OK_TUL
	 from LOCATION_INVENTORY LI
	 left outer join location L on L.location = LI.LOCATION
	 where LI.warehouse  = 'Tultitlan'AND L.location_CLASS = 'Inventory'	
	 group by LI.ITEM) OKTUL ON OKTUL.ITEM = SD.ITEM



	 LEFT OUTER JOIN (	 select item,sum(on_hand_qty) AS TOTAL_QTY_PRE01_MAR
	 from LOCATION_INVENTORY LI
	 left outer join location L on L.location = LI.LOCATION
	 where LI.warehouse  = 'Mariano' AND L.location = 'PRE-01'
	 group by LI.ITEM) PRMAR ON PRMAR.ITEM = SD.ITEM


	 LEFT OUTER JOIN WORK_INSTRUCTION WI ON WI.LAUNCH_NUM = SD.PREVIOUS_WAVE_NUM AND WI.COMPANY = SD.COMPANY AND WI.ITEM = SD.ITEM

	WHERE ALLOCATION_REJECTED_QTY <> '0.00000' AND LI.WAREHOUSE = 'Mariano' AND SD.warehouse = 'Mariano' AND location_CLASS = 'Inventory' AND LI.LOCATION IN (SELECT DISTINCT LOCATION FROM LOCATION_INVENTORY)
	
	GROUP BY PREVIOUS_WAVE_NUM, SHIPMENT_ID, SD.ITEM, WORK_ZONE,LS.LAUNCH_DATE_TIME_STARTED,OKMAR.TOTAL_QTY_OK_MAR,OKTUL.TOTAL_QTY_OK_TUL,PRMAR.TOTAL_QTY_PRE01_MAR,SD.ALLOCATION_REJECTED_QTY,WI.WORK_UNIT, WI.WORK_TYPE,LI.PERMANENT