INSERT INTO item_cross_reference (ITEM, X_REF_ITEM, COMPANY, USER_STAMP, DATE_TIME_STAMP, QUANTITY_UM, GTIN_ENABLED)
VALUES 
-- ('ITEM', 'CODIGO_DE_BARRAS', 'FM', 'JoseCarlos', DATEADD(HOUR, 6, GETDATE()), 'PZ', 'N'),





-- DATEADD(HOUR, 6, GETDATE())



SELECT
ICR.ITEM, ICR.X_REF_ITEM, I.ITEM_COLOR
FROM ITEM_CROSS_REFERENCE ICR
INNER JOIN ITEM I ON I.ITEM = ICR.ITEM

WHERE ICR.COMPANY = 'FM'
AND ICR.ITEM LIKE '6426-%'
AND I.COMPANY = 'FM'