SELECT 
  WAREHOUSE, LOCATION, ITEM, ITEM_COLOR, COMPANY,
  CAST(SUM(AV) AS INT) AS AV,
  CAST(SUM(OH) AS INT) AS OH,
  CAST(SUM(AL) AS INT) AS AL,
  CAST(SUM(IT) AS INT) AS IT,
  CAST(SUM(SU) AS INT) AS SU,
  HUELLA,
  CAJAS

FROM 
(
SELECT
  LI.WAREHOUSE,
  LI.LOCATION,
  LI.ITEM,
  LI.ITEM_COLOR,
  LI.COMPANY,
  ((LI.ON_HAND_QTY + LI.IN_TRANSIT_QTY) -  (LI.ALLOCATED_QTY + LI.SUSPENSE_QTY)) AS AV,
  LI.ON_HAND_QTY AS OH,
  LI.ALLOCATED_QTY AS AL,
  LI.IN_TRANSIT_QTY AS IT,
  LI.SUSPENSE_QTY AS SU,
  LI.internal_location_inv,
  UOM.conversion_qty AS HUELLA,
  CAST((LI.on_hand_qty / UOM.conversion_qty) AS DECIMAL(5, 2)) AS CAJAS
 

FROM location_inventory LI
INNER JOIN location L
 ON L.location = LI.location

INNER JOIN Item_unit_of_measure UOM
 ON LI.item = UOM.item

WHERE LI.warehouse='Tultitlan'
AND L.work_zone = 'W-Tul Producto Terminado'
AND UOM.sequence = '2'


GROUP BY LI.WAREHOUSE, LI.LOCATION, LI.ITEM,
  LI.ITEM_COLOR,
  LI.COMPANY,
  LI.ON_HAND_QTY,
  LI.ALLOCATED_QTY,
  LI.IN_TRANSIT_QTY,
  LI.SUSPENSE_QTY,
  LI.internal_location_inv,
  LI.logistics_Unit,
  UOM.sequence,
   UOM.conversion_qty

) AS PRINCIPAL

WHERE CAJAS <> ROUND(CAJAS, 0)
AND CAJAS < 1



GROUP BY WAREHOUSE, LOCATION, ITEM, ITEM_COLOR, COMPANY, HUELLA, CAJAS

ORDER BY 3, 2

-- WAREHOUSE,LOCATION,ITEM,ITEM_COLOR,COMPANY,AV,OH,AL,IT,SU,HUELLA,CAJAS,