SELECT
    ITEM,
    sequence,

    LENGTH AS LENGTH_ACTUAL,
    CASE
        WHEN LENGTH > 70 THEN 70
        ELSE LENGTH
    END AS LENGTH_NUEVO,

    WIDTH AS WIDTH_ACTUAL,
    CASE
        WHEN WIDTH > 58 THEN 58
        ELSE WIDTH
    END AS WIDTH_NUEVO,

    HEIGHT AS HEIGHT_ACTUAL,
    CASE
        WHEN HEIGHT > 69 THEN 69
        ELSE HEIGHT
    END AS HEIGHT_NUEVO

FROM item_unit_of_measure

WHERE COMPANY = 'FM'
  AND sequence <> '3'
  AND ITEM LIKE '10034-%'
  AND (
       LENGTH > 70
       OR WIDTH > 58
       OR HEIGHT > 69
  );


-- ===========================

UPDATE item_unit_of_measure
SET 
    LENGTH = CASE WHEN LENGTH > 70 THEN 70 ELSE LENGTH END,
    WIDTH  = CASE WHEN WIDTH > 58 THEN 58 ELSE WIDTH END,
    HEIGHT = CASE WHEN HEIGHT > 69 THEN 69 ELSE HEIGHT END

WHERE COMPANY = 'FM'
  AND SEQUENCE <> '3'
  AND ITEM LIKE '10034-%'
  AND (
      LENGTH > 70
      OR WIDTH > 58
      OR HEIGHT > 69
  );
