SELECT DISTINCT
I.ITEM, I.DESCRIPTION, I.company AS COMPANY_ITEM , CAST(UOM.conversion_qty AS INT) AS HUELLA, UOM.QUANTITY_UM, UOM.company AS COMPANY_HUELLA

FROM item I
INNER JOIN Item_unit_of_measure UOM ON I.ITEM=UOM.item

WHERE UOM.sequence='2'
AND I.company='FM'
AND UOM.company='FM'
AND (
  I.ITEM LIKE '5157-%' OR
)

-- @headers: ITEM, DESCRIPTION, COMPANY, COMPANY_ITEM, HUELLA, QUANTITY_UM, COMPANY_HUELLA,
